apiVersion: apps/v1
kind: Deployment
metadata:
  name: ganapati_kyndryl_23
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ganapati_kyndryl_23
  template:
    metadata:
      labels:
        app: ganapati_kyndryl_23
    spec:
      containers:
        - name: ganapati_kyndryl_23
          image: your-docker-image
          ports:
            - containerPort: 8080
